[package]
name = "machine-learning"
version = "0.1.0"
authors = ["Miguel K"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra="*"
smartcore="*"