code --install-extension bungcip.better-toml
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension felipecaputo.git-project-manager
code --install-extension matklad.rust-analyzer
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-bicep
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-vscode.azurecli
code --install-extension mutantdino.resourcemonitor
code --install-extension oderwat.indent-rainbow
code --install-extension redhat.vscode-yaml
code --install-extension serayuzgur.crates
code --install-extension vadimcn.vscode-lldb
code --install-extension wraith13.bracket-lens